### ISSUE TITLE
Crash when sorting  sessions

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#145] opened 2018-07-28 04:47 UTC
When I view the sessions of the last three months and sort them by hour descending, gbm crashes.
Weird thing is, it’s working, when I
* first sort the week view descending
* then increase the time period to three months
* then stort by hour ascending
-> when I switch to descending, it crashes again.

I first thought, I had faulty entries in my database,  but sorting by hour ascending should crash as well

```
Located in /usr/bin
Could not get XIM
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at GBM.frmSessions+RowCompareHelper.Compare (System.Object x, System.Object y) [0x00032] in <5c126e1cce174aecb99783daf20ff3db>:0 
  at System.Array+SorterObjectArray.PickPivotAndPartition (System.Int32 lo, System.Int32 hi) [0x0003b] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array+SorterObjectArray.IntroSort (System.Int32 lo, System.Int32 hi, System.Int32 depthLimit) [0x0005a] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array+SorterObjectArray.IntroSort (System.Int32 lo, System.Int32 hi, System.Int32 depthLimit) [0x00063] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array+SorterObjectArray.IntroSort (System.Int32 lo, System.Int32 hi, System.Int32 depthLimit) [0x00063] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array+SorterObjectArray.IntrospectiveSort (System.Int32 left, System.Int32 length) [0x0001b] in <1050938ab6ed42698bde160668e4367c>:0 
   --- End of inner exception stack trace ---
  at System.Array+SorterObjectArray.IntrospectiveSort (System.Int32 left, System.Int32 length) [0x0003d] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array+SorterObjectArray.Sort (System.Int32 left, System.Int32 length) [0x00000] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array.SortImpl (System.Array keys, System.Array items, System.Int32 index, System.Int32 length, System.Collections.IComparer comparer) [0x00027] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array.Sort (System.Array keys, System.Array items, System.Int32 index, System.Int32 length, System.Collections.IComparer comparer) [0x0009d] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Array.Sort (System.Array array, System.Int32 index, System.Int32 length, System.Collections.IComparer comparer) [0x00000] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Collections.ArrayList.Sort (System.Int32 index, System.Int32 count, System.Collections.IComparer comparer) [0x0004d] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Collections.ArrayList.Sort (System.Collections.IComparer comparer) [0x00008] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Windows.Forms.DataGridViewRowCollection.Sort (System.Collections.IComparer comparer) [0x0002c] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.DataGridView.Sort (System.Collections.IComparer comparer) [0x0004a] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at GBM.frmSessions.DoSort (System.Boolean& bToggle, System.Int32 iCol, GBM.frmSessions+RowCompareHelper+iDataType iType) [0x00049] in <5c126e1cce174aecb99783daf20ff3db>:0 
  at GBM.frmSessions.HandleSort (System.Int32 iCol) [0x0004b] in <5c126e1cce174aecb99783daf20ff3db>:0 
  at GBM.frmSessions.dgSessions_ColumnHeaderMouseClick (System.Object sender, System.Windows.Forms.DataGridViewCellMouseEventArgs e) [0x00007] in <5c126e1cce174aecb99783daf20ff3db>:0 
  at System.Windows.Forms.DataGridView.OnColumnHeaderMouseClick (System.Windows.Forms.DataGridViewCellMouseEventArgs e) [0x00054] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.DataGridView.OnMouseClick (System.Windows.Forms.MouseEventArgs e) [0x00139] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.Control.HandleClick (System.Int32 clicks, System.Windows.Forms.MouseEventArgs me) [0x00048] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x0006b] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001b4] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.DataGridView.WndProc (System.Windows.Forms.Message& m) [0x00000] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <240efc5058be4d25afeb1ace92c31a98>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <240efc5058be4d25afeb1ace92c31a98>:0 

```

**Comment by MikeMaximus** [comment] 2018-07-28 13:54
Strange,  it looks like it crashing because of a null row.  But then i'm not sure why a specific sequence would be needed to make it crash.

I tried using my data, various date formats, on both Windows and Linux and I can't make it crash.  I may need to your database (just from /.local/share/gbm) to troubleshoot this.  You can e-mail it if you don't want to attach it publicly.

**Comment by MikeMaximus** [comment] 2018-08-22 13:34
Are you still having issues with this?  I'm going to do a new release soon, I can try and get a fix in but I still can't reproduce this error.

**Comment by basxto** [comment] 2018-08-22 22:46
Yes, sorry.
I wanted to delete all irrelevant sessions, but did not do that.
I have now limited it to one day with 30 entries or so.
Many very short sessions, several of the same length.
The crash did not occur when I filtered by game name.

This is how it looks when it crashes:
![2018-08-23_00 21_914x623](https://user-images.githubusercontent.com/1314450/44494673-01676700-a66d-11e8-87fe-0c94068b5985.png)

And the compressed database for 2018-06-27:
[gbm.nullref.s3db.zip](https://github.com/MikeMaximus/gbm/files/2312210/gbm.nullref.s3db.zip)

**Comment by MikeMaximus** [comment] 2018-08-23 14:13
I can't replicate the issue on Ubuntu 16.04 or 18.04 with your data either.  Both use old versions of Mono (v4.0 and v4.6)  I'm setting up a test environment with Antergos so I can test with the same version of Mono that the AUR provides, which seems to be 5+.  Once I can replicate the problem maybe I can work-around whatever got changed or broken.

**Comment by basxto** [comment] 2018-08-23 14:55
Arch has sqlite, p7zip and mono in their official repositories. mono-basic and gbm are in AUR.

It’s likely quicker to set up a graphical desktop with Antergos than with Arch.

Manually installing from AUR should be something like: (base-devel contains sudo)
$ su -c "pacman -S base-devel p7zip sqlite imagemagick"
$ git clone https://aur.archlinux.org/mono-basic.git
$ git clone https://aur.archlinux.org/gbm.git
$ cd mono-basic
$ makepkg -si
$ cd ../gbm
$ makepkg -si
$ gbm

As root you don’t need the su -c
I will update to the latest mono version later and test again.

Are there any other files who could be needed?

**Comment by MikeMaximus** [comment] 2018-08-23 15:02
I got it all setup and i'm able to reproduce the crash.  I'll see what I can do now.

**Comment by basxto** [comment] 2018-08-23 15:16
```
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object
```
https://msdn.microsoft.com/en-us/library/fd85b3df.aspx

`dgRow1.Cells(iSortCol).Value` is the only method call I see, is that be related to the empty row in my screenshot?

**Comment by MikeMaximus** [comment] 2018-08-23 16:05
I got it fixed now,  seems the new version of Mono doesn't like how I was doing the sort logic for numeric values.

**Comment by MikeMaximus** [comment] 2018-08-23 16:28
The new logic works on all version of Mono I tested and shouldn't be an issue again.

**Closed by MikeMaximus** 2018-08-23 16:28 UTC
Labels: bug, linux

**Comment by MikeMaximus** [comment] 2018-08-23 18:58
Just as a side note, I'm glad I had to install Antergos to fix this.  It might become my new main environment for general work and testing.  It's just so snappy performance wise in VirtualBox compared to Ubuntu, which feels like slow motion to me now.

**Comment by basxto** [comment] 2018-08-24 16:00
Antergos likely has less software installed and running than Ubuntu. As far as I can see, they only added an graphical installer and a graphical package manager, but use Arch's repositories for the rest.
Arch can be pretty quick, but Ubuntu and debian are easier to use and get started with. They change software, they ship with standard configurations which should work for most people. Services usually start after installing them.

For testing your upcomming release you would just need to alter a few things in the PKGBUILD:
```bash
pkgver=1.1.4
source=("GBM.v${pkgver}.32-bit.7z") #use file in same folder, no download
sha256sums=('SKIP') #no need
```

But I would rather use Ubuntu LTS for testing, which gets released every 2 years and receives updates for 5 years. Then you can say it’s running with a certain version and it should work for quite an amount of people.
Antergos is rolling release like Arch Linux and with them your results are less reproducible and out-dated sooner.

Also keep in mind that games on gog, humble and steam usually only support one or multiple LTS versions of Ubuntu. Other distributions usually work and get fixed, but they are not guaranteed to work or get tested. [It's not uncommon for games to break because libraries are too new or packages are missing, which are installed on Ubuntu by default.](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting)

**Comment by basxto** [comment] 2018-08-24 16:09
I can confirm that it’s working now.
Thank you.

**Comment by MikeMaximus** [comment] 2018-08-24 16:27
Great!  You're right in regards to testing with Ubuntu.  I should continue doing that.

I did test the pkgbuild right after I uploaded the new version to make sure it would work by editing those values.  I didn't know I could provide a local source path, so in the future i'll test that before I actually submit the release.
